### ISSUE TITLE
Validator is not checking is "items" key is present for "array" data types

### ISSUE THREAD

**Issue by AlstonLin** [Yelp/swagger_spec_validator#84] opened 2017-11-30 00:09 UTC
For example this will pass the validator
```
...
foo:
    type: array
...
```
However, this should fail according to the [swagger specification](https://swagger.io/docs/specification/data-models/data-types/#array) as `items` is a required key for any `array` types

**Comment by bplotnick** [comment] 2018-06-06 01:34
@macisamuele I think this was duped by #94 and fixed in #95, right?

**Comment by macisamuele** [comment] 2018-06-06 05:43
@bplotnick you are correct.
Closing this as duplicate of #94

**Closed by macisamuele** 2018-06-06 05:43 UTC
