### ISSUE TITLE
Validator does not check uniqueness of operation ids

### ISSUE THREAD

**Issue by ngaya-ll** [Yelp/swagger_spec_validator#85] opened 2017-12-22 21:55 UTC
According to the Swagger spec, the `operationId` of an operation object is:

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

The validator does not currently check that `operationId`s are unique across the API.  This would be a helpful feature because some codegen tools fail if this constraint is not met.

**Comment by bradj** [comment] 2018-02-21 21:37
Just confirmed that this is still an issue.

**Comment by macisamuele** [comment] 2018-06-05 13:25
The merged PR does not completely address the _duplicate operation id_ issue as it ensures that no duplicate operation ids are present on the same tag.

**Comment by mattmetlis** [comment] 2021-07-23 01:37
Is anyone able to look at this PR? I believe it addresses the rest of the issue.

**Comment by mattmetlis** [comment] 2021-07-27 17:53
@analogue @sjaensch It looks like you are some of the most recent people who have merged pull requests in this project (if I'm reading the network graph correctly). Could you please take a look at this, or is there another maintainer you know of who can? This PR has a fix that's important for my company, and I haven't gotten any response on it since I submitted it more than a week ago.

**Comment by sjaensch** [comment] 2021-07-27 19:57
@mattmetlis I don't have write access to the repository anymore, @analogue might be able to help out though.

**Comment by mattmetlis** [comment] 2021-08-02 23:38
Is there anyone else you know of who has write access? This is looking like an abandoned project.

**Closed** 2021-10-09 01:46 UTC
